// SPDX-License-Identifier: LGPLv3
pragma solidity ^0.8.19;

/**
 * @title ILiquidityPosition
 * @notice Interface for liquidity position management
 * @dev Defines the structure and interactions when LPs provide assets to a DEX pool via this system.
 */
interface ILiquidityPosition {
    // ========== STRUCTS ==========\n    \n    struct Position {\n        uint256 positionId;         // DEX NFT token ID\n        address lpProvider;         // LP who provided sDAI\n        address userProvider;       // User who provided wsXMR\n        uint256 sDAIAmount;         // sDAI in position\n        uint256 wsxmrAmount;        // wsXMR in position\n        uint256 lpInitialValueUSD;  // LP's initial contribution value\n        uint256 userInitialValueUSD;// User's initial contribution value\n        uint256 createdAt;          // Creation timestamp\n    }\n    \n    // ========== EVENTS ==========\n    \n    event PositionCreated(\n        uint256 indexed positionIndex,\n        uint256 dexTokenId,\n        address indexed lp,\n        address indexed user,\n        uint256 sDAIAmount,\n        uint256 wsxmrAmount\n    );\n    \n    event PositionClosed(\n        uint256 indexed positionIndex,\n        uint256 sDAIReturned,\n        uint256 wsxmrReturned\n    );\n    \n    event FeesCollected(\n        uint256 indexed positionIndex,\n        uint256 sDAIFees,\n        uint256 wsxmrFees\n    );\n    \n    event FeesWithdrawn(\n        address indexed recipient,\n        uint256 sDAIAmount,\n        uint256 wsxmrAmount\n    );\n    \n    // ========== ERRORS ==========\n    \n    error PositionNotFound();\n    error PositionTooYoung();\n    error BelowCallerMinimum();\n    error WithdrawalValueTooLow();\n    \n    // ========== FUNCTIONS ==========\n    \n    /// @notice Create position with fresh price update\n    function createPositionWithPriceUpdate(\n        address lp,\n        address user,\n        uint256 sDAIAmount,\n        uint256 wsxmrAmount,\n        uint256 deadline,\n        bytes[] calldata pythUpdateData\n    ) external payable returns (uint256 positionIndex);\n    \n    /// @notice Create position (requires recent price update)\n    function createPosition(\n        address lp,\n        address user,\n        uint256 sDAIAmount,\n        uint256 wsxmrAmount,\n        uint256 deadline\n    ) external returns (uint256 positionIndex);\n    \n    /// @notice Close a position and return assets\n    function closePosition(\n        uint256 positionIndex,\n        uint256 deadline,\n        uint256 minTotalValueUSD\n    ) external;\n    \n    /// @notice Collect fees from active position\n    function collectFees(uint256 positionIndex) external;\n    \n    /// @notice Withdraw accumulated fees\n    function withdrawFees() external;\n    \n    // VIEW FUNCTIONS (Kept for completeness)\n    function getPosition(uint256 positionIndex) external view returns (Position memory);\n    function getUserPositions(\n        address account,\n        uint256 cursor,\n        uint256 limit\n    ) external view returns (Position[] memory positions, uint256 nextCursor);\n    function getPendingFees(address account) external view returns (\n        uint256 sDAIFees,\n        uint256 wsxmrFees\n    );\n}