const { ethers } = require('ethers');

const target = '0x19abf40e';

const errors = [
    'ZeroAddress()',
    'ZeroAmount()',
    'VaultDoesNotExist()',
    'InsufficientCollateral()',
    'InsufficientDebt()',
    'InsufficientBond()',
    'InsufficientDeposit()',
    'InvalidValue()',
    'InvalidSecret()',
    'InvalidStatus()',
    'Unauthorized()',
    'DeadlineExpired()',
    'OnlyHub()',
    'InvalidCommitment()',
    'BurnExceedsVaultDebt()',
    'StalePrices()',
    'InvalidPrice()',
    'PositionNotFound()',
    'InvalidRange()',
    'InvalidConfig()',
    'PriceTooOld()',
    'PriceTooHigh()',
    'PriceTooLow()',
    'NoActiveMint()',
    'MintAlreadyReady()',
    'MintTimeout()',
    'MintNotReady()',
    'NoActiveBurn()',
    'BurnTimeout()',
    'BurnNotCommitted()',
    'AlreadyFinalized()',
    'InvalidProof()',
    'InvalidSignature()',
    'InvalidBlockHeight()',
    'InvalidAmount()',
    'InvalidRecipient()',
    'TransferFailed()',
    'RedeemFailed()',
    'DepositFailed()',
    'SwapFailed()',
    'SlippageExceeded()',
    'InvalidRatio()',
    'NoDebt()',
    'NotLiquidatable()',
    'LiquidationNotInitiated()',
    'LiquidationTimeout()',
    'LiquidationAlreadyComplete()',
    'YieldSyncFailed()',
    'MaxCoLPRangeExceeded()',
    'NoPositions()',
    'NoPendingReturns()',
    'MintCapExceeded()',
    'InvalidTickRange()',
    'PoolNotFound()',
    'PoolAlreadyExists()',
    'InvalidFeeTier()',
    'InvalidOracle()',
    'OracleNotSet()',
    'InvalidFacet()',
    'FacetAlreadyExists()',
    'FacetNotFound()',
    'FunctionDoesNotExist()',
    'InvalidDelegate()',
    'DelegateAlreadyExists()',
    'InvalidContract()',
    'InvalidAddress()',
    'InvalidParam()',
    'InvalidState()',
    'NotAllowed()',
    'Paused()',
    'ReentrantCall()',
];

for (const err of errors) {
    const hash = ethers.utils.id(err);
    if (hash.slice(0, 10) === target) {
        console.log('MATCH:', err, hash);
    }
}

console.log('No match found in common errors');
