const { ethers } = require('ethers');

const selector = '0x19abf40e';

// Common custom errors - try to find the matching one
const candidates = [
    'StalePrices()',
    'InvalidPrice()',
    'ZeroAmount()',
    'VaultDoesNotExist()',
    'InsufficientCollateral()',
    'PositionNotFound()',
    'Unauthorized()',
    'DeadlineExpired()',
    'InvalidRange()',
    'InvalidConfig()',
    'PriceTooOld()',
    'PriceTooHigh()',
    'PriceTooLow()',
    'NoActiveMint()',
    'MintAlreadyReady()',
    'MintTimeout()',
    'MintNotReady()',
    'NoActiveBurn()',
    'BurnTimeout()',
    'BurnNotCommitted()',
    'AlreadyFinalized()',
    'InvalidProof()',
    'InvalidSignature()',
    'InvalidBlockHeight()',
    'InvalidAmount()',
    'InvalidRecipient()',
    'TransferFailed()',
    'RedeemFailed()',
    'DepositFailed()',
    'SwapFailed()',
    'SlippageExceeded()',
    'InvalidRatio()',
    'NoDebt()',
    'NotLiquidatable()',
    'LiquidationNotInitiated()',
    'LiquidationTimeout()',
    'LiquidationAlreadyComplete()',
    'YieldSyncFailed()',
    'MaxCoLPRangeExceeded()',
    'NoPositions()',
    'NoPendingReturns()',
    'MintCapExceeded()',
    'InvalidTickRange()',
    'PoolNotFound()',
    'PoolAlreadyExists()',
    'InvalidFeeTier()',
    'InvalidOracle()',
    'OracleNotSet()',
    'InvalidFacet()',
    'FacetAlreadyExists()',
    'FacetNotFound()',
    'FunctionDoesNotExist()',
    'InvalidDelegate()',
    'DelegateAlreadyExists()',
    'InvalidContract()',
    'InvalidAddress()',
    'InvalidParam()',
    'InvalidState()',
    'NotAllowed()',
    'Paused()',
    'ReentrantCall()',
    'ArithmeticOverflow()',
    'DivisionByZero()',
    'OutOfBounds()',
    'InvalidLength()',
    'EmptyArray()',
    'DuplicateEntry()',
    'NotInitialized()',
    'AlreadyInitialized()',
    'UpgradeFailed()',
    'ImplementationNotFound()',
    'ProxyCallFailed()',
    'InvalidVersion()',
    'VersionMismatch()',
    'InvalidData()',
    'CallFailed()',
    'StaticcallFailed()',
    'DelegatecallFailed()',
    'CreateFailed()',
    'InvalidSelector()',
    'InvalidValue()',
    'InvalidType()',
    'InvalidHash()',
    'InvalidSignatureLength()',
    'InvalidNonce()',
    'NonceAlreadyUsed()',
    'NonceTooHigh()',
    'NonceTooLow()',
    'InvalidDeadline()',
    'ExpiredDeadline()',
    'InvalidPath()',
    'InvalidRoute()',
    'InvalidPool()',
    'InvalidToken()',
    'InvalidAmountOut()',
    'InvalidAmountIn()',
    'InvalidSlippage()',
    'InvalidLiquidity()',
    'InvalidTick()',
    'InvalidSqrtPrice()',
    'InvalidFee()',
    'InvalidProtocolFee()',
    'InvalidObservation()',
    'InvalidCardinality()',
    'InvalidIndex()',
    'InvalidBlockNumber()',
    'InvalidTimestamp()',
    'InvalidGasPrice()',
    'InvalidBaseFee()',
    'InvalidPriorityFee()',
    'InvalidChainId()',
    'InvalidSender()',
    'InvalidReceiver()',
    'InvalidOwner()',
    'InvalidSpender()',
    'InvalidOperator()',
    'InvalidApprover()',
    'InvalidSignatureType()',
    'InvalidSignatureVersion()',
    'InvalidSignatureRecovery()',
    'InvalidSignatureSValue()',
    'InvalidSignatureVValue()',
    'InvalidPermit()',
    'InvalidAllowance()',
    'InvalidBalance()',
    'InvalidSupply()',
    'InvalidDecimals()',
    'InvalidName()',
    'InvalidSymbol()',
    'InvalidMetadata()',
    'InvalidURI()',
    'InvalidTokenId()',
    'InvalidApproval()',
    'InvalidTransfer()',
    'InvalidMint()',
    'InvalidBurn()',
    'InvalidWithdraw()',
    'InvalidDeposit()',
    'InvalidRedeem()',
    'InvalidHarvest()',
    'InvalidCompound()',
    'InvalidRebalance()',
    'InvalidSwap()',
    'InvalidAddLiquidity()',
    'InvalidRemoveLiquidity()',
    'InvalidCollect()',
    'InvalidFlash()',
    'InvalidLock()',
    'InvalidUnlock()',
    'InvalidClaim()',
    'InvalidStake()',
    'InvalidUnstake()',
    'InvalidReward()',
    'InvalidEpoch()',
    'InvalidPeriod()',
    'InvalidInterval()',
    'InvalidDuration()',
    'InvalidCooldown()',
    'InvalidFee()',
    'InvalidPenalty()',
    'InvalidBonus()',
    'InvalidMultiplier()',
    'InvalidCap()',
    'InvalidFloor()',
    'InvalidCeiling()',
    'InvalidThreshold()',
    'InvalidLimit()',
    'InvalidTarget()',
    'InvalidRef()',
    'InvalidProof()',
    'InvalidRoot()',
    'InvalidLeaf()',
    'InvalidBranch()',
    'InvalidCommitment()',
    'InvalidNullifier()',
    'InvalidTrapdoor()',
    'InvalidMerkleRoot()',
    'InvalidMerkleProof()',
    'InvalidMerkleBranch()',
    'InvalidMerkleLeaf()',
    'InvalidAccumulator()',
    'InvalidAccumulatorValue()',
    'InvalidAccumulatorWitness()',
    'InvalidAccumulatorInput()',
    'InvalidAccumulatorOutput()',
    'InvalidAccumulatorState()',
    'InvalidAccumulatorProof()',
    'InvalidAccumulatorUpdate()',
    'InvalidAccumulatorReset()',
    'InvalidAccumulatorInit()',
    'InvalidAccumulatorCommit()',
    'InvalidAccumulatorDecommit()',
    'InvalidAccumulatorVerify()',
    'InvalidAccumulatorChallenge()',
    'InvalidAccumulatorResponse()',
    'InvalidAccumulatorRandom()',
    'InvalidAccumulatorSeed()',
    'InvalidAccumulatorKey()',
    'InvalidAccumulatorPublicKey()',
    'InvalidAccumulatorPrivateKey()',
    'InvalidAccumulatorSecret()',
    'InvalidAccumulatorParams()',
    'InvalidAccumulatorConfig()',
    'InvalidAccumulatorSettings()',
    'InvalidAccumulatorOptions()',
    'InvalidAccumulatorMetadata()',
    'InvalidAccumulatorData()',
    'InvalidAccumulatorInput()',
    'InvalidAccumulatorOutput()',
    'InvalidAccumulatorState()',
    'InvalidAccumulatorProof()',
    'InvalidAccumulatorWitness()',
    'InvalidAccumulatorValue()',
    'InvalidAccumulatorChallenge()',
    'InvalidAccumulatorResponse()',
    'InvalidAccumulatorRandom()',
    'InvalidAccumulatorSeed()',
    'InvalidAccumulatorKey()',
    'InvalidAccumulatorPublicKey()',
    'InvalidAccumulatorPrivateKey()',
    'InvalidAccumulatorSecret()',
    'InvalidAccumulatorParams()',
    'InvalidAccumulatorConfig()',
    'InvalidAccumulatorSettings()',
    'InvalidAccumulatorOptions()',
    'InvalidAccumulatorMetadata()',
    'InvalidAccumulatorData()',
];

for (const sig of candidates) {
    const hash = ethers.utils.id(sig);
    if (hash.startsWith(selector)) {
        console.log('MATCH:', sig, '->', hash);
    }
}

// Also try the exact 4-byte match
const exactFourByte = selector.slice(0, 10);
console.log('\nSearching for exact 4-byte match:', exactFourByte);
for (const sig of candidates) {
    const hash = ethers.utils.id(sig);
    if (hash.slice(0, 10) === exactFourByte) {
        console.log('EXACT MATCH:', sig, '->', hash);
    }
}

// Try some known errors from the contracts
const contractErrors = [
    'error StalePrices()',
    'error InvalidPrice()',
    'error ZeroAmount()',
    'error VaultDoesNotExist()',
    'error InsufficientCollateral()',
    'error PositionNotFound()',
    'error Unauthorized()',
    'error DeadlineExpired()',
    'error InvalidRange()',
    'error InvalidConfig()',
    'error PriceTooOld()',
    'error PriceTooHigh()',
    'error PriceTooLow()',
    'error NoActiveMint()',
    'error MintAlreadyReady()',
    'error MintTimeout()',
    'error MintNotReady()',
    'error NoActiveBurn()',
    'error BurnTimeout()',
    'error BurnNotCommitted()',
    'error AlreadyFinalized()',
    'error InvalidProof()',
    'error InvalidSignature()',
    'error InvalidBlockHeight()',
    'error InvalidAmount()',
    'error InvalidRecipient()',
    'error TransferFailed()',
    'error RedeemFailed()',
    'error DepositFailed()',
    'error SwapFailed()',
    'error SlippageExceeded()',
    'error InvalidRatio()',
    'error NoDebt()',
    'error NotLiquidatable()',
    'error LiquidationNotInitiated()',
    'error LiquidationTimeout()',
    'error LiquidationAlreadyComplete()',
    'error YieldSyncFailed()',
    'error MaxCoLPRangeExceeded()',
    'error NoPositions()',
    'error NoPendingReturns()',
    'error MintCapExceeded()',
    'error InvalidTickRange()',
    'error PoolNotFound()',
    'error PoolAlreadyExists()',
    'error InvalidFeeTier()',
    'error InvalidOracle()',
    'error OracleNotSet()',
    'error InvalidFacet()',
    'error FacetAlreadyExists()',
    'error FacetNotFound()',
    'error FunctionDoesNotExist()',
    'error InvalidDelegate()',
    'error DelegateAlreadyExists()',
    'error InvalidContract()',
    'error InvalidAddress()',
    'error InvalidParam()',
    'error InvalidState()',
    'error NotAllowed()',
    'error Paused()',
    'error ReentrantCall()',
    'error ArithmeticOverflow()',
    'error DivisionByZero()',
    'error OutOfBounds()',
    'error InvalidLength()',
    'error EmptyArray()',
    'error DuplicateEntry()',
    'error NotInitialized()',
    'error AlreadyInitialized()',
    'error UpgradeFailed()',
    'error ImplementationNotFound()',
    'error ProxyCallFailed()',
    'error InvalidVersion()',
    'error VersionMismatch()',
    'error InvalidData()',
    'error CallFailed()',
    'error StaticcallFailed()',
    'error DelegatecallFailed()',
    'error CreateFailed()',
    'error InvalidSelector()',
    'error InvalidValue()',
    'error InvalidType()',
    'error InvalidHash()',
    'error InvalidSignatureLength()',
    'error InvalidNonce()',
    'error NonceAlreadyUsed()',
    'error NonceTooHigh()',
    'error NonceTooLow()',
    'error InvalidDeadline()',
    'error ExpiredDeadline()',
    'error InvalidPath()',
    'error InvalidRoute()',
    'error InvalidPool()',
    'error InvalidToken()',
    'error InvalidAmountOut()',
    'error InvalidAmountIn()',
    'error InvalidSlippage()',
    'error InvalidLiquidity()',
    'error InvalidTick()',
    'error InvalidSqrtPrice()',
    'error InvalidFee()',
    'error InvalidProtocolFee()',
    'error InvalidObservation()',
    'error InvalidCardinality()',
    'error InvalidIndex()',
    'error InvalidBlockNumber()',
    'error InvalidTimestamp()',
    'error InvalidGasPrice()',
    'error InvalidBaseFee()',
    'error InvalidPriorityFee()',
    'error InvalidChainId()',
    'error InvalidSender()',
    'error InvalidReceiver()',
    'error InvalidOwner()',
    'error InvalidSpender()',
    'error InvalidOperator()',
    'error InvalidApprover()',
    'error InvalidSignatureType()',
    'error InvalidSignatureVersion()',
    'error InvalidSignatureRecovery()',
    'error InvalidSignatureSValue()',
    'error InvalidSignatureVValue()',
    'error InvalidPermit()',
    'error InvalidAllowance()',
    'error InvalidBalance()',
    'error InvalidSupply()',
    'error InvalidDecimals()',
    'error InvalidName()',
    'error InvalidSymbol()',
    'error InvalidMetadata()',
    'error InvalidURI()',
    'error InvalidTokenId()',
    'error InvalidApproval()',
    'error InvalidTransfer()',
    'error InvalidMint()',
    'error InvalidBurn()',
    'error InvalidWithdraw()',
    'error InvalidDeposit()',
    'error InvalidRedeem()',
    'error InvalidHarvest()',
    'error InvalidCompound()',
    'error InvalidRebalance()',
    'error InvalidSwap()',
    'error InvalidAddLiquidity()',
    'error InvalidRemoveLiquidity()',
    'error InvalidCollect()',
    'error InvalidFlash()',
    'error InvalidLock()',
    'error InvalidUnlock()',
    'error InvalidClaim()',
    'error InvalidStake()',
    'error InvalidUnstake()',
    'error InvalidReward()',
    'error InvalidEpoch()',
    'error InvalidPeriod()',
    'error InvalidInterval()',
    'error InvalidDuration()',
    'error InvalidCooldown()',
    'error InvalidFee()',
    'error InvalidPenalty()',
    'error InvalidBonus()',
    'error InvalidMultiplier()',
    'error InvalidCap()',
    'error InvalidFloor()',
    'error InvalidCeiling()',
    'error InvalidThreshold()',
    'error InvalidLimit()',
    'error InvalidTarget()',
    'error InvalidRef()',
    'error InvalidProof()',
    'error InvalidRoot()',
    'error InvalidLeaf()',
    'error InvalidBranch()',
    'error InvalidCommitment()',
    'error InvalidNullifier()',
    'error InvalidTrapdoor()',
    'error InvalidMerkleRoot()',
    'error InvalidMerkleProof()',
    'error InvalidMerkleBranch()',
    'error InvalidMerkleLeaf()',
    'error InvalidAccumulator()',
    'error InvalidAccumulatorValue()',
    'error InvalidAccumulatorWitness()',
    'error InvalidAccumulatorInput()',
    'error InvalidAccumulatorOutput()',
    'error InvalidAccumulatorState()',
    'error InvalidAccumulatorProof()',
    'error InvalidAccumulatorUpdate()',
    'error InvalidAccumulatorReset()',
    'error InvalidAccumulatorInit()',
    'error InvalidAccumulatorCommit()',
    'error InvalidAccumulatorDecommit()',
    'error InvalidAccumulatorVerify()',
    'error InvalidAccumulatorChallenge()',
    'error InvalidAccumulatorResponse()',
    'error InvalidAccumulatorRandom()',
    'error InvalidAccumulatorSeed()',
    'error InvalidAccumulatorKey()',
    'error InvalidAccumulatorPublicKey()',
    'error InvalidAccumulatorPrivateKey()',
    'error InvalidAccumulatorSecret()',
    'error InvalidAccumulatorParams()',
    'error InvalidAccumulatorConfig()',
    'error InvalidAccumulatorSettings()',
    'error InvalidAccumulatorOptions()',
    'error InvalidAccumulatorMetadata()',
    'error InvalidAccumulatorData()',
    'error InvalidAccumulatorInput()',
    'error InvalidAccumulatorOutput()',
    'error InvalidAccumulatorState()',
    'error InvalidAccumulatorProof()',
    'error InvalidAccumulatorWitness()',
    'error InvalidAccumulatorValue()',
    'error InvalidAccumulatorChallenge()',
    'error InvalidAccumulatorResponse()',
    'error InvalidAccumulatorRandom()',
    'error InvalidAccumulatorSeed()',
    'error InvalidAccumulatorKey()',
    'error InvalidAccumulatorPublicKey()',
    'error InvalidAccumulatorPrivateKey()',
    'error InvalidAccumulatorSecret()',
    'error InvalidAccumulatorParams()',
    'error InvalidAccumulatorConfig()',
    'error InvalidAccumulatorSettings()',
    'error InvalidAccumulatorOptions()',
    'error InvalidAccumulatorMetadata()',
    'error InvalidAccumulatorData()',
];

// Try to match by computing keccak256 of the error signature
for (const sig of contractErrors) {
    // Extract just the error name and params
    const match = sig.match(/error\s+(\w+)\((.*)\)/);
    if (match) {
        const name = match[1];
        const params = match[2];
        const signature = `${name}(${params})`;
        const hash = ethers.utils.id(signature);
        if (hash.slice(0, 10) === exactFourByte) {
            console.log('EXACT MATCH:', signature, '->', hash);
        }
    }
}

// Print the selector we're looking for
console.log('\nLooking for selector:', exactFourByte);
